name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - 
        name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      -
        name: install requirements
        run: pip install -r requirements.txt
      - 
        name: build
        run: python main.py
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/go-station.csv
